# Generated by Django 3.2.4 on 2024-03-14 04:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0006_auto_20240304_1628"),
    ]

    operations = [
        migrations.CreateModel(
            name="Backup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("host_ip", models.CharField(default="", max_length=100, verbose_name="备份主机IP")),
                ("dir", models.CharField(default="", max_length=100, verbose_name="备份目录")),
                ("suffix", models.CharField(default="", max_length=100, verbose_name="备份名后缀")),
                ("backup_user", models.CharField(default="", max_length=100, verbose_name="备份人")),
                ("backup_time", models.DateTimeField(default=django.utils.timezone.now, verbose_name="备份时间")),
                ("backup_files", models.CharField(default="", max_length=100, verbose_name="备份文件名")),
                ("job_link", models.CharField(default="", max_length=100, verbose_name="JOB链接")),
                ("job_instance_id", models.CharField(default="", max_length=100, verbose_name="job_instance_id")),
            ],
        ),
        migrations.DeleteModel(
            name="TestModel",
        ),
    ]
