# Generated by Django 3.2.4 on 2024-03-17 03:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0007_auto_20240314_1256"),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("biz_name", models.CharField(default="", max_length=100)),
                ("biz_id", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sync_time", models.DateTimeField(default=django.utils.timezone.now, verbose_name="同步时间")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("SYNCING", "Syncing"),
                            ("FAIL", "Fail"),
                            ("SUCCESS", "Success"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="host",
            name="biz_id",
        ),
        migrations.RemoveField(
            model_name="host",
            name="biz_name",
        ),
        migrations.RemoveField(
            model_name="host",
            name="module_id",
        ),
        migrations.RemoveField(
            model_name="host",
            name="module_name",
        ),
        migrations.RemoveField(
            model_name="host",
            name="set_id",
        ),
        migrations.RemoveField(
            model_name="host",
            name="set_name",
        ),
        migrations.CreateModel(
            name="Set",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("set_name", models.CharField(default="", max_length=100)),
                ("set_id", models.IntegerField(unique=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sets", to="home_application.business"
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="home_application.version",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("module_name", models.CharField(default="", max_length=100)),
                ("module_id", models.IntegerField(unique=True)),
                ("hosts", models.ManyToManyField(related_name="modules", to="home_application.Host")),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="modules", to="home_application.set"
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="home_application.version",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="business",
            name="version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="businesses",
                to="home_application.version",
            ),
        ),
        migrations.AddField(
            model_name="host",
            name="version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hosts",
                to="home_application.version",
            ),
        ),
    ]
